title: "Workshop SynBio 2025"
author: "Organizado por Christian Cuba y Jennyfer Arismendiz"
logo: images/logo.png        # si tienes un logo, colÃ³calo en una carpeta llamada 'images'
repository:
  url: https://github.com/polarbbio/SynBio-2025
  path_to_book: .
html:
  navbar_number_sections: true
  use_repository_button: true
  extra_footer: "Â© 2025 Workshop SynBio Â· SynBioWorld ðŸŒ±"
